language: go
go:
- 1.6.3
go_import_path: github.com/ndslabs
env:
  global:
  - secure: xc1HoUaq7B3NdtpZn9U9ld3sY+IJa3/SOurv2PESILJqONO501qzwIzekWb9X5cCKmn2IXdnE2JK/RCh71zqIqMUh0ngNvwFjoWeyS9lI/Llbs59XQu9idVgvd6LHGvULxTzOvqWsERydW40z+xfZnCmG3Vvf0NPe1+fi+l5FmtW0U6vuIPHbFcYhLDLD6X9sKO1cSPiGir6iLDFLVTX+t/zr1Z259igv3oupsqp3CXIp4A/eARETR+p5T/kH/0HU2EgennrnxA5azn2uTQmFcu2NyseU4UPuGgr0lcHCF1r35o2nweXg4JQj0f1t88hNcb4qCym7VmVwEO8OUyp3CmGPaA/eP7QNhj2F/2V8bphov79j+lq+Y7CoOjeVpO5r4wJ9XFD81T3wX1e3fqyPLdIwSKxFAUCQpGSjNvBWMfStYrpu4En62YZLab+PTItF2Uq+FSldFW9HLPjZ+nyv5qSehYW35GWrmvxVqhxW5YJHc+bXHxYA4Ob5wJL3KBdyBSWKVftU+zX3wt2IZEfFrUTtZkv4Gr/Y/bmCmp6ZwEx6KLL2WJdsdS0DYvLXYIiO8zmRUmVGAvHEEWe44FoOFx8pHleRVAXrxM69qsSyriE0U8PScZ667SmZV8k/dVeF4fyH+cVuXhY3eYfYI8JssAM3NYuGaRZfPPWxl0g3mM=
  - secure: roRL6MnN0QvrmmlJnpJ+6gHLN9XQH9Qm132HeFPRMiIV4bqERAhQtNydoNEeRofFnPmDagSPTw5jHwwi1pj9bXO+/R94T4hGUAscYoRe5IAlmBidsJSH8MNvJs042ygEy9fFvND5fJCNj8bYi19iQkbJu7bqIW26Og9s/AtaKzdIC+92iYfmYJ5ZknLL/GjfAZ7juBB60f9EVvos0Z1qxAfhYgyRjlwf0Sx5IKw+/G2H4csFTKTbSeXYuiL1CDmmk6iHqqKHKwtLrxAbgVzqDwAVvcy5YyK84Oh/GCUHdluOY3FNt4mYwptQMEF/dBOTPRX16cjPwQ8Gto+n0UYO6V//rHRd86wn4UB0mimb54aieuTrYK3W6KaK42uSo0io6pmp8s1OUanSuFN1IUQCp6JEvgHrJHrvDNlXvp4sme0qU95x6D+9SM0525hGmuzDEsO5HJV9SOhThbUIcRvd7gI5i14PWMBrwhuof9h+gi5uuNC9cN74qEe4ldR4XVowa0lTE3sqYEXwDh97dmrR4RS7NmI1qqhRP8JQtgPqFsKpPLv2Nvten5buPlnSQBycHUQOaZluB0hL6xf3NtfwMAoTF7yFSzsrnJiUxwMcW5yDC5Mw3fWx0z+dyQ8YN8g757iN5tLKiO+3KtlnnMY2jweops1XCZ1jM0qMpEOcqX8=
install:
- go get github.com/Masterminds/glide
script:
- cd apictl && ./build.sh local
after_success:
- pwd
- ls -lR
- curl --ftp-create-dirs -T apictl/build/bin/*amd64 -u $FTP_USER:$FTP_PASSWORD sftp://141.142.208.183/releases/$TRAVIS_BRANCH
